version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: php-${APP_ENV}
    user: "1000:1000"
    depends_on:
      - elasticsearch
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/app:rw
      - home-dir:/home/user
    working_dir: /app
    environment:
      HOME: /home/user
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
    networks:
      - default
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    user: "1000:1000"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.flood_stage=200mb
      - cluster.routing.allocation.disk.watermark.low=500mb
      - cluster.routing.allocation.disk.watermark.high=300mb
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - default
  cerebro:
    image: lmenezes/cerebro
    ports:
     - "9002:9000"

networks:
  default:
    driver: bridge

volumes:
  elasticsearch-data:
  home-dir:
